/*
 * DMI Employees
 * CRUD operations with DMI employees
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseCode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeesApi
 */
@Ignore
public class EmployeesApiTest {

    private final EmployeesApi api = new EmployeesApi();

    
    /**
     * Get the dmi employees information
     *
     * Get employees info
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesIdGetTest() throws ApiException {
        Integer id = null;
        String authorization = null;
        ResponseCode response = api.employeesIdGet(id, authorization);

        // TODO: test validations
    }
    
}
